<?php

namespace Eamirgh\Optimus\Drivers;

use RuntimeException;
use GdImage;

class GdDriver extends AbstractDriver
{
    public function supportedFormats(): array
    {
        $formats = ['jpeg', 'jpg', 'png', 'gif'];
        if (function_exists('imagewebp')) {
            $formats[] = 'webp';
        }
        if (function_exists('imageavif')) {
            $formats[] = 'avif';
        }
        return $formats;
    }

    public function process(string $sourceBinaryOrPath, array $options = []): string
    {
        $image = $this->loadSourceImage($sourceBinaryOrPath);

        $srcWidth = imagesx($image);
        $srcHeight = imagesy($image);

        $targetWidth = $options['width'] ?? null;
        $targetHeight = $options['height'] ?? null;
        $fit = $options['fit'] ?? 'cover';
        $format = strtolower($options['format'] ?? 'webp');
        $quality = $options['quality'] ?? 80;

        [$destW, $destH, $srcX, $srcY, $srcW, $srcH] = $this->calculateDimensions(
            $srcWidth,
            $srcHeight,
            $targetWidth,
            $targetHeight,
            $fit
        );

        $canvas = imagecreatetruecolor($destW, $destH);

        // Retain alpha channel for PNG/WebP/GIF
        imagealphablending($canvas, false);
        imagesavealpha($canvas, true);
        $transparent = imagecolorallocatealpha($canvas, 255, 255, 255, 127);
        imagefilledrectangle($canvas, 0, 0, $destW, $destH, $transparent);

        imagecopyresampled(
            $canvas,
            $image,
            0, 0,
            $srcX, $srcY,
            $destW, $destH,
            $srcW, $srcH
        );

        $output = $this->encodeImage($canvas, $format, $quality);

        imagedestroy($image);
        imagedestroy($canvas);

        return $output;
    }

    public function generateUrl(string $sourcePath, array $options = []): string
    {
        // For local GD driver, route URL is generated by OptimusUrlGenerator
        return '';
    }

    protected function loadSourceImage(string $sourceBinaryOrPath): GdImage
    {
        if (file_exists($sourceBinaryOrPath)) {
            $binary = file_get_contents($sourceBinaryOrPath);
        } else {
            $binary = $sourceBinaryOrPath;
        }

        $image = @imagecreatefromstring($binary);
        if ($image === false) {
            throw new RuntimeException('Failed to load image: invalid or corrupt image binary/path.');
        }

        return $image;
    }

    protected function encodeImage(GdImage $image, string $format, int $quality): string
    {
        ob_start();

        switch ($format) {
            case 'webp':
                if (! function_exists('imagewebp')) {
                    throw new RuntimeException('WebP support is missing in current GD installation.');
                }
                imagewebp($image, null, $quality);
                break;

            case 'avif':
                if (! function_exists('imageavif')) {
                    // Fallback to webp if avif not in GD
                    if (function_exists('imagewebp')) {
                        imagewebp($image, null, $quality);
                        break;
                    }
                    imagejpeg($image, null, $quality);
                    break;
                }
                imageavif($image, null, $quality);
                break;

            case 'png':
                // PNG compression is 0 (no compression) to 9
                $pngQuality = (int) round((100 - $quality) / 11.11);
                $pngQuality = max(0, min(9, $pngQuality));
                imagepng($image, null, $pngQuality);
                break;

            case 'gif':
                imagegif($image, null);
                break;

            case 'jpg':
            case 'jpeg':
            default:
                imagejpeg($image, null, $quality);
                break;
        }

        $output = ob_get_clean();
        if ($output === false || $output === '') {
            throw new RuntimeException("Failed to encode image in {$format} format.");
        }

        return $output;
    }
}
